// cake_library_ex/frontend/src/components/AUTH/Login.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/services/store/Auth/auth'

const router = useRouter()
const authStore = useAuthStore()

const emit = defineEmits(['close', 'switch-to-register'])

const credentials = ref({
  email: '',
  password: ''
})

const handleLogin = async () => {
  try {
    await authStore.login(credentials.value)
    router.push('/dashboard')
  } catch (error) {
    console.error('Login failed:', error)
  }
}
</script>

<template>
  <div class="login-modal-overlay">
    <div class="login-modal">
      <div class="modal-left">
        <div class="image-overlay">
          <h3 class="quote">"Embrace the art of cooking, where flavors come alive!"</h3>
        </div>
      </div>

      <div class="modal-right">
        <button class="close-btn" @click="emit('close')" aria-label="Close">×</button>
        
        <h2>Login</h2>
        <p class="subtitle">Enter your email to log in.</p>

        <form @submit.prevent="handleLogin">
          <div class="form-group">
            <input 
              id="email"
              v-model="credentials.email" 
              type="email" 
              placeholder="Enter your email" 
              required 
            />
          </div>

          <div class="form-group">
            <input 
              id="password"
              v-model="credentials.password" 
              type="password" 
              placeholder="Enter your password" 
              required 
            />
          </div>

          <button type="submit" class="continue-btn" :disabled="authStore.loading">
            {{ authStore.loading ? 'Logging in...' : 'Continue' }}
          </button>

          <p v-if="authStore.error" class="error">{{ authStore.error }}</p>

          <div class="register-link">
            <p>
              Don't have an account? 
              <a href="#" @click.prevent="emit('switch-to-register')">Register here</a>
            </p>
          </div>

          <p class="terms">
            By continuing, you agree to the updated 
            <a href="#">Terms of Sale</a>, 
            <a href="#">Terms of Service</a>, and 
            <a href="#">Privacy Policy</a>.
          </p>
        </form>
      </div>
    </div>
  </div>
</template>

<style scoped>
.login-modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.login-modal {
  display: flex;
  width: 100%;
  max-width: 900px;
  height: 600px;
  background: white;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.modal-left {
  flex: 1;
  background: linear-gradient(135deg, rgba(102, 186, 189, 0.9) 0%, rgba(78, 162, 165, 0.9) 100%),
              url('/lily-banse--YHSwy6uqvk-unsplash.png') center/cover;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 40px;
  position: relative;
}

.image-overlay {
  text-align: center;
  z-index: 1;
}

.quote {
  color: white;
  font-size: 28px;
  font-weight: 300;
  line-height: 1.5;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
  max-width: 350px;
}

.modal-right {
  flex: 1;
  padding: 50px 60px;
  overflow-y: auto;
  position: relative;
}

.close-btn {
  position: absolute;
  top: 20px;
  right: 20px;
  background: none;
  border: none;
  font-size: 32px;
  color: #999;
  cursor: pointer;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: color 0.2s;
}

.close-btn:hover {
  color: #333;
}

h2 {
  margin-bottom: 8px;
  color: #1a1a1a;
  font-size: 32px;
  font-weight: 600;
}

.subtitle {
  color: #666;
  margin-bottom: 30px;
  font-size: 14px;
}

.form-group {
  margin-bottom: 16px;
}

input {
  width: 100%;
  padding: 14px 16px;
  border: 1px solid #e0e0e0;
  border-radius: 6px;
  font-size: 15px;
  transition: border-color 0.2s;
  box-sizing: border-box;
}

input:focus {
  outline: none;
  border-color: #1a237e;
}

input::placeholder {
  color: #999;
}

.continue-btn {
  width: 100%;
  padding: 14px;
  background: #1a237e;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 16px;
  font-weight: 500;
  cursor: pointer;
  margin-top: 8px;
  transition: background 0.2s;
}

.continue-btn:hover:not(:disabled) {
  background: #0d47a1;
}

.continue-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.error {
  color: #d32f2f;
  text-align: center;
  margin-top: 12px;
  font-size: 14px;
}

.register-link {
  text-align: center;
  margin: 24px 0;
  padding: 20px 0;
  border-top: 1px solid #e0e0e0;
}

.register-link p {
  color: #666;
  font-size: 14px;
  margin: 0;
}

.register-link a {
  color: #1a237e;
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s;
}

.register-link a:hover {
  color: #0d47a1;
  text-decoration: underline;
}

.terms {
  font-size: 12px;
  color: #666;
  text-align: center;
  margin: 20px 0 0 0;
  line-height: 1.5;
}

.terms a {
  color: #1a237e;
  text-decoration: none;
}

.terms a:hover {
  text-decoration: underline;
}

@media (max-width: 768px) {
  .login-modal {
    flex-direction: column;
    height: auto;
    max-height: 90vh;
  }

  .modal-left {
    min-height: 200px;
    padding: 30px;
  }

  .quote {
    font-size: 20px;
  }

  .modal-right {
    padding: 30px;
  }

  h2 {
    font-size: 24px;
  }
}
</style>

// microservices/commerce/web_interface/src/components/Overall/Login.svelte
<script>

</script>

<div class="form-container">
  <!-- Login Panel -->
  <div class="login-panel">
    <form class="log-in">
      <label for="email">Email *</label>
      <input type="email" id="email" name="email" required>
      <span class="input-info">Enter your registered email address.</span>

      <label for="password">Password *</label>
      <input type="password" id="password" name="password" required>
      <span class="input-info">Enter your password.</span>

      <button type="submit">Login</button>
    </form>
  </div>

  <!-- Content / Info Panel -->
  <div class="content-panel">
    <h2>Welcome Back!</h2>
    <p>Login to access your dashboard.</p>
  </div>
</div>

<style>
body, html {
    height: 100%;
    margin: 0;
    font-family: 'Verdana', sans-serif;
    background-color: #f5f5f5;
}

.form-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 90vh;
    gap: 50px;
    padding: 40px;
}

.content-panel {
    flex: 1;
    max-width: 400px;
    text-align: center;
}

.content-panel h2 {
    font-size: 2rem;
    margin-bottom: 15px;
}

.content-panel p {
    font-size: 1rem;
    color: #555;
}

.login-panel {
    flex: 1;
    max-width: 400px;
    padding: 40px 50px 40px 40px;
    border: 1px solid #ccc;
    border-radius: 10px;
    box-shadow: 0px 5px 15px rgba(0,0,0,0.1);
    background-color: #fff;
}

label {
    display: block;
    margin-bottom: 5px;
    font-weight: 500;
    color: #ff0202;
}

input {
    padding: 7px;
    border-radius: 7px;
    border: 1px solid #999;
    font-size: 1rem;
    outline: none;
    width: 100%;
    margin-bottom: 5px;
    transition: border 0.3s;
}

input:focus {
    border: 2px solid #4caf50;
}

.input-info {
    display: block;
    font-size: 0.85rem;
    color: #555;
    margin-bottom: 15px;
}

button {
    width: 100%;
    padding: 12px;
    font-size: 1rem;
    font-weight: bold;
    color: #fff;
    background-color: #4caf50;
    border: none;
    border-radius: 7px;
    cursor: pointer;
    transition: background-color 0.3s;
}

button:hover {
    background-color: #45a049;
}

@media (max-width: 900px) {
    .form-container {
        flex-direction: column;
        gap: 20px;
    }
}
</style>
